[package]
name = "mpl"
version = "0.2.0"
authors = ["Kazuki Kurota"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Minimal parser combinator of Minimal Parsing Language (MPL) like Top-Down Parsing Language (TDPL)."
readme = "../../README.md"
repository = "https://github.com/kurotakazuki/mpl"
categories = ["parsing"]
keywords = ["combinator", "generator", "grammar", "parser", "tdpl"]

[dependencies]
