[package]
name = "mpl-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
# TODO Remove extra-trait features
syn = { version = "1.0", features = ["extra-traits"] }
mpl = { path = "../mpl" }
