[package]
name = "paren"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpl = { path = "../../packages/mpl" }
mpl-macro = { path = "../../packages/mpl-macro" }